### ISSUE TITLE
Add automatic commit in npm-release

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/npm-automation#4]
Add automatic commit in [npm-release](https://github.com/deep-foundation/npm-automation/blob/9c72523c106377f10566244a7a6c37132b646a12/src/npm-release.ts)

**Comment by Konard** [comment]
It should also do git add, git commit, git push and git push for tags. Example (it is bad example because it does not do push tags) https://github.com/deep-foundation/npm-packager/blob/2cbc05c9d1dcf7ff25230476cee487cf4e29a116/package.json#L11 Example with tags: ```
npm version patch && git push && git push --tags
```
